// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SkipGameCardFeature")]
    public partial class SkipGameCardFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SkipGameCardFeature.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SkipGameCardFeature", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Playing a skip card with non skip cards in the play pile should only skip one pla" +
            "yer")]
        [NUnit.Framework.CategoryAttribute("bugtest")]
        public virtual void PlayingASkipCardWithNonSkipCardsInThePlayPileShouldOnlySkipOnePlayer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Playing a skip card with non skip cards in the play pile should only skip one pla" +
                    "yer", new string[] {
                        "bugtest"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Player",
                        "CardsInHand"});
            table1.AddRow(new string[] {
                        "Ed",
                        "ThreeOfClubs, FiveOfClubs"});
            table1.AddRow(new string[] {
                        "Liam",
                        "FourOfClubs"});
            table1.AddRow(new string[] {
                        "Dave",
                        "FourOfClubs"});
#line 5
 testRunner.Given("I have the following players and cards", ((string)(null)), table1, "Given ");
#line 10
 testRunner.And("it is \'Liam\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CardValue",
                        "Rule"});
            table2.AddRow(new string[] {
                        "Five",
                        "SkipPlayer"});
#line 11
 testRunner.And("the following cards have rules", ((string)(null)), table2, "And ");
#line 14
 testRunner.When("\'Liam\' plays the \'FourOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("\'Dave\' plays the \'FourOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("\'Ed\' plays the \'FiveOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.Then("it should be \'Dave\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Playing two skip cards with non skip cards in play pile should skip two players")]
        [NUnit.Framework.CategoryAttribute("bugtest")]
        public virtual void PlayingTwoSkipCardsWithNonSkipCardsInPlayPileShouldSkipTwoPlayers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Playing two skip cards with non skip cards in play pile should skip two players", new string[] {
                        "bugtest"});
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Player",
                        "CardsInHand"});
            table3.AddRow(new string[] {
                        "Ed",
                        "ThreeOfClubs, FiveOfClubs, FiveOfClubs"});
            table3.AddRow(new string[] {
                        "Liam",
                        "FourOfClubs"});
            table3.AddRow(new string[] {
                        "Dave",
                        "FourOfClubs"});
#line 21
 testRunner.Given("I have the following players and cards", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "CardValue",
                        "Rule"});
            table4.AddRow(new string[] {
                        "Five",
                        "SkipPlayer"});
#line 27
 testRunner.And("the following cards have rules", ((string)(null)), table4, "And ");
#line 30
 testRunner.And("it is \'Liam\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("\'Liam\' plays the \'FourOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("\'Dave\' plays the \'FourOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("\'Ed\' plays the \'FiveOfClubs, FiveOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.Then("it should be \'Ed\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("PLaying one skip card after a previous player plays a skip card should only skip " +
            "one player")]
        public virtual void PLayingOneSkipCardAfterAPreviousPlayerPlaysASkipCardShouldOnlySkipOnePlayer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PLaying one skip card after a previous player plays a skip card should only skip " +
                    "one player", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Player",
                        "CardsInHand"});
            table5.AddRow(new string[] {
                        "Ed",
                        "FiveOfClubs"});
            table5.AddRow(new string[] {
                        "Liam",
                        "FourOfClubs"});
            table5.AddRow(new string[] {
                        "Dave",
                        "FiveOfClubs"});
#line 37
testRunner.Given("I have the following players and cards", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "CardValue",
                        "Rule"});
            table6.AddRow(new string[] {
                        "Five",
                        "SkipPlayer"});
#line 42
 testRunner.And("the following cards have rules", ((string)(null)), table6, "And ");
#line 45
 testRunner.And("it is \'Ed\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.When("\'Ed\' plays the \'FiveOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.And("\'Dave\' plays the \'FiveOfClubs\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.Then("it should be \'Liam\' turn", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
